config/routes.rb
Rails.application.routes.draw do
  root 'players#index'

  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end

  def new
  	@player = Player.new
  end

  def create
  	@player = Player.new(player_params)
  	if @player.save
  		redirect_to root_path
  	end
  end

  def show
  	@player = Player.find_by(id: params[:id])
  end

  def edit
  	@player = Player.find_by(id: params[:id])
  end

  def update
  	@player = Player.find_by(id: params[:id])
  	if @player.update
  		redirect_to  edit_player_path(:params)
  	end
  end

  def destroy
  	@player = Player.find_by(id: params[:id])
  	if @player.destroy
  		redirect_to player_path(:params)
  	end
  end
private
  def player_params
    params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: players_path do |f| %>
  <%= label_tag :nickname %>
  <%= f.text_field :nickname %><br />
  <%= label_tag :rank %>
  <%= f.text_field :rank %><br />
  <%= label_tag :charisma %>
  <%= f.text_field :charisma %><br />
  <%= label_tag :wisdom %>
  <%= f.text_field :wisdom %><br />
  <%= f.submit "Create" %><br />
<% end %>

app/views/players/index.html.erb
<% if @players == [] %>
    <p>Don't find players </p>
<% else %>
    <% @players.each do |player| %> 
      <%= player.nickname %><br />
      <%= player.rank %><br />
      <%= link_to "Show", player_path(player.id)%></p>
    <% end %>
<% end %>
<%= link_to "New player",  new_player_path %>

app/views/players/new.html.erb
<%= form_for @player, url: players_path do |f| %>
  <%= label_tag :nickname %>
  <%= f.text_field :nickname %><br />
  <%= label_tag :rank %>
  <%= f.text_field :rank %><br />
  <%= label_tag :charisma %>
  <%= f.text_field :charisma %><br />
  <%= label_tag :wisdom %>
  <%= f.text_field :wisdom %><br />
  <%= f.submit "Create" %><br />
<% end %>

app/views/players/show.html.erb
<p>
	Player : <%= @player.nickname %><br />
	Rank : <%= @player.rank%><br />
	Charisma : <%= @player.charisma%><br />
	Wisdom : <%= @player.wisdom%><br />
</p>
<p>
	<%= link_to "Edit", edit_player_path(player.id)%>
	<%= link_to "Delete", player_path(player.id) method: delete%>
</p>